version: '3.8'

services:
  # ===== BASE DE DATOS =====
  mysql-central:
    image: mysql:8.0
    container_name: hospital-mysql-central
    environment:
      MYSQL_ROOT_PASSWORD: SuperRootPassword123!
      MYSQL_DATABASE: hospital_central
      MYSQL_USER: admin_central
      MYSQL_PASSWORD: SuperPasswordCentral123!
    ports:
      - "3307:3306"
    volumes:
      - mysql_central_data:/var/lib/mysql
      - ./sql/central.sql:/docker-entrypoint-initdb.d/01-central.sql
    networks:
      - hospital-network
    restart: unless-stopped

  mysql-guayaquil:
    image: mysql:8.0
    container_name: hospital-mysql-guayaquil
    environment:
      MYSQL_ROOT_PASSWORD: SuperRootPassword123!
      MYSQL_DATABASE: hospital_guayaquil
      MYSQL_USER: admin_guayaquil
      MYSQL_PASSWORD: SuperPasswordGye123!
    ports:
      - "3308:3306"
    volumes:
      - mysql_guayaquil_data:/var/lib/mysql
      - ./sql/guayaquil.sql:/docker-entrypoint-initdb.d/01-guayaquil.sql
    networks:
      - hospital-network
    restart: unless-stopped

  mysql-cuenca:
    image: mysql:8.0
    container_name: hospital-mysql-cuenca
    environment:
      MYSQL_ROOT_PASSWORD: SuperRootPassword123!
      MYSQL_DATABASE: hospital_cuenca
      MYSQL_USER: admin_cuenca
      MYSQL_PASSWORD: SuperPasswordCuenca123!
    ports:
      - "3309:3306"
    volumes:
      - mysql_cuenca_data:/var/lib/mysql
      - ./sql/cuenca.sql:/docker-entrypoint-initdb.d/01-cuenca.sql
    networks:
      - hospital-network
    restart: unless-stopped

  # ===== MICROSERVICIOS =====
  api-gateway:
    build: ./api-gateway
    container_name: hospital-api-gateway
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=SuperJWTSecret123!
      - AUTH_SERVICE_URL=http://auth-service:3002
      - ADMIN_SERVICE_URL=http://admin-service:3003
      - CONSULTAS_SERVICE_URL=http://consultas-service:3004
      - USERS_SERVICE_URL=http://users-service:3005
      - REPORTS_SERVICE_URL=http://reports-service:3006
    depends_on:
      - auth-service
      - admin-service
      - consultas-service
      - users-service
      - reports-service
    networks:
      - hospital-network
    restart: unless-stopped

  auth-service:
    build: ./auth-service
    container_name: hospital-auth-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - JWT_SECRET=SuperJWTSecret123!
      - DB_HOST=mysql-central
      - DB_USER=admin_central
      - DB_PASSWORD=SuperPasswordCentral123!
      - DB_PORT=3306
      - DB_NAME=hospital_central
    depends_on:
      - mysql-central
    networks:
      - hospital-network
    restart: unless-stopped

  admin-service:
    build: ./admin-service
    container_name: hospital-admin-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - JWT_SECRET=SuperJWTSecret123!
      - DB_HOST=mysql-central
      - DB_USER=admin_central
      - DB_PASSWORD=SuperPasswordCentral123!
      - DB_PORT=3306
      - DB_NAME=hospital_central
      - DB_GUAYAQUIL_HOST=mysql-guayaquil
      - DB_GUAYAQUIL_USER=admin_guayaquil
      - DB_GUAYAQUIL_PASSWORD=SuperPasswordGye123!
      - DB_GUAYAQUIL_PORT=3306
      - DB_GUAYAQUIL_NAME=hospital_guayaquil
      - DB_CUENCA_HOST=mysql-cuenca
      - DB_CUENCA_USER=admin_cuenca
      - DB_CUENCA_PASSWORD=SuperPasswordCuenca123!
      - DB_CUENCA_PORT=3306
      - DB_CUENCA_NAME=hospital_cuenca
    depends_on:
      - mysql-central
      - mysql-guayaquil
      - mysql-cuenca
    networks:
      - hospital-network
    restart: unless-stopped

  consultas-service:
    build: ./consultas-service
    container_name: hospital-consultas-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
      - JWT_SECRET=SuperJWTSecret123!
      - DB_HOST=mysql-central
      - DB_USER=admin_central
      - DB_PASSWORD=SuperPasswordCentral123!
      - DB_PORT=3306
      - DB_NAME=hospital_central
      - DB_GUAYAQUIL_HOST=mysql-guayaquil
      - DB_GUAYAQUIL_USER=admin_guayaquil
      - DB_GUAYAQUIL_PASSWORD=SuperPasswordGye123!
      - DB_GUAYAQUIL_PORT=3306
      - DB_GUAYAQUIL_NAME=hospital_guayaquil
      - DB_CUENCA_HOST=mysql-cuenca
      - DB_CUENCA_USER=admin_cuenca
      - DB_CUENCA_PASSWORD=SuperPasswordCuenca123!
      - DB_CUENCA_PORT=3306
      - DB_CUENCA_NAME=hospital_cuenca
    depends_on:
      - mysql-central
      - mysql-guayaquil
      - mysql-cuenca
    networks:
      - hospital-network
    restart: unless-stopped

  users-service:
    build: ./users-service
    container_name: hospital-users-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - PORT=3005
      - JWT_SECRET=SuperJWTSecret123!
      - DB_HOST=mysql-central
      - DB_USER=admin_central
      - DB_PASSWORD=SuperPasswordCentral123!
      - DB_PORT=3306
      - DB_NAME=hospital_central
      - DB_GUAYAQUIL_HOST=mysql-guayaquil
      - DB_GUAYAQUIL_USER=admin_guayaquil
      - DB_GUAYAQUIL_PASSWORD=SuperPasswordGye123!
      - DB_GUAYAQUIL_PORT=3306
      - DB_GUAYAQUIL_NAME=hospital_guayaquil
      - DB_CUENCA_HOST=mysql-cuenca
      - DB_CUENCA_USER=admin_cuenca
      - DB_CUENCA_PASSWORD=SuperPasswordCuenca123!
      - DB_CUENCA_PORT=3306
      - DB_CUENCA_NAME=hospital_cuenca
    depends_on:
      - mysql-central
      - mysql-guayaquil
      - mysql-cuenca
    networks:
      - hospital-network
    restart: unless-stopped

  reports-service:
    build: ./reports-service
    container_name: hospital-reports-service
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - PORT=3006
      - JWT_SECRET=SuperJWTSecret123!
      - DB_HOST=mysql-central
      - DB_USER=admin_central
      - DB_PASSWORD=SuperPasswordCentral123!
      - DB_PORT=3306
      - DB_NAME=hospital_central
      - DB_GUAYAQUIL_HOST=mysql-guayaquil
      - DB_GUAYAQUIL_USER=admin_guayaquil
      - DB_GUAYAQUIL_PASSWORD=SuperPasswordGye123!
      - DB_GUAYAQUIL_PORT=3306
      - DB_GUAYAQUIL_NAME=hospital_guayaquil
      - DB_CUENCA_HOST=mysql-cuenca
      - DB_CUENCA_USER=admin_cuenca
      - DB_CUENCA_PASSWORD=SuperPasswordCuenca123!
      - DB_CUENCA_PORT=3306
      - DB_CUENCA_NAME=hospital_cuenca
    depends_on:
      - mysql-central
      - mysql-guayaquil
      - mysql-cuenca
    networks:
      - hospital-network
    restart: unless-stopped

  # ===== FRONTEND ÚNICO =====
  frontend:
    build: 
      context: ../frontend/vite-project
      dockerfile: Dockerfile
    container_name: hospital-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3003
    depends_on:
      - api-gateway
    networks:
      - hospital-network
    restart: unless-stopped

volumes:
  mysql_central_data:
  mysql_guayaquil_data:
  mysql_cuenca_data:

networks:
  hospital-network:
    driver: bridge
